version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate proto files"
    cmds:
       - |
        export GOROOT=/usr/local/go
        export GOPATH=$HOME/go
        export GOBIN=$GOPATH/bin
        export PATH=$PATH:$GOROOT:$GOPATH:$GOBIN
        protoc -I proto proto/sso/*.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative
